// frontend/src/components/sessions/session-filters.tsx
import { useState, useEffect } from 'react'
import { Search, X, SlidersHorizontal } from 'lucide-react'
import { useStore } from '@/store'

interface SessionFiltersProps {
  instances: string[]
}

export function SessionFilters({ instances }: SessionFiltersProps) {
  const { filters, setFilters } = useStore()
  const [showFilters, setShowFilters] = useState(false)
  
  // Debounced search - local state for immediate UI, debounce to store
  const [searchInput, setSearchInput] = useState(filters.search)
  
  // Sync local search with store (debounced)
  useEffect(() => {
    const timer = setTimeout(() => {
      if (searchInput !== filters.search) {
        setFilters({ search: searchInput })
      }
    }, 300)
    return () => clearTimeout(timer)
  }, [searchInput, filters.search, setFilters])
  
  // Sync store → local when filters cleared externally
  useEffect(() => {
    if (filters.search !== searchInput && filters.search === '') {
      setSearchInput('')
    }
  }, [filters.search])
  
  const hasFilters = filters.hostname || filters.status || searchInput

  const activeFilterCount = [
    filters.hostname ? 1 : 0,
    filters.status ? 1 : 0,
    filters.search ? 1 : 0
  ].filter(Boolean).length

  const handleClear = () => {
    setSearchInput('')
    setFilters({ hostname: null, status: null, search: '' })
  }

  return (
    <div className="space-y-3">
      {/* Mobile: Compact search with filter toggle */}
      <div className="lg:hidden space-y-3">
        <div className="flex gap-2 items-center">
          <div className="relative flex-1">
            <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 size-3.5 text-muted-foreground" />
            <input
              type="text"
              placeholder="Search sessions..."
              value={searchInput}
              onChange={(e) => setSearchInput(e.target.value)}
              className="w-full h-8 pl-8 pr-3 rounded-md border border-border bg-background text-xs placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-primary"
            />
          </div>

          <button
            onClick={() => setShowFilters(!showFilters)}
            className="h-8 px-2 rounded-md border border-border bg-background text-muted-foreground hover:text-foreground hover:bg-muted transition-colors shrink-0 relative"
            aria-label={showFilters ? 'Hide filters' : 'Show filters'}
          >
            <SlidersHorizontal className="size-3.5" />
            {activeFilterCount > 0 && (
              <span className="absolute -top-1 -right-1 h-4 w-4 rounded-full bg-primary text-[10px] text-primary-foreground flex items-center justify-center">
                {activeFilterCount}
              </span>
            )}
          </button>
        </div>

        {hasFilters && (
          <button
            onClick={handleClear}
            className="h-8 px-2 rounded-md text-xs text-muted-foreground hover:text-foreground hover:bg-muted transition-colors flex items-center gap-1.5"
          >
            <X className="size-3.5" />
            Clear filters
          </button>
        )}
      </div>

      {/* Collapsible filters - mobile only */}
      {showFilters && (
        <div className="lg:hidden space-y-3 pt-2 border-t">
          <div className="grid grid-cols-2 gap-2">
            <select
              value={filters.hostname || ''}
              onChange={(e) => setFilters({ hostname: e.target.value || null })}
              className="h-8 px-2.5 rounded-md border border-border bg-background text-xs focus:outline-none focus:ring-1 focus:ring-primary"
            >
              <option value="">All instances</option>
              {instances.map((h) => (
                <option key={h} value={h}>{h}</option>
              ))}
            </select>

            <select
              value={filters.status || ''}
              onChange={(e) => setFilters({ status: e.target.value || null })}
              className="h-8 px-2.5 rounded-md border border-border bg-background text-xs focus:outline-none focus:ring-1 focus:ring-primary"
            >
              <option value="">All status</option>
              <option value="active">Active</option>
              <option value="idle">Idle</option>
              <option value="error">Error</option>
            </select>
          </div>
        </div>
      )}

      {/* Desktop: Full filters always visible */}
      <div className="hidden lg:flex flex-wrap items-center gap-3">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 size-4 text-muted-foreground" />
          <input
            type="text"
            placeholder="Search sessions..."
            value={searchInput}
            onChange={(e) => setSearchInput(e.target.value)}
            className="w-full h-9 pl-9 pr-3 rounded-md border border-border bg-background text-sm placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-primary"
          />
        </div>

        <select
          value={filters.hostname || ''}
          onChange={(e) => setFilters({ hostname: e.target.value || null })}
          className="h-9 px-3 rounded-md border border-border bg-background text-sm focus:outline-none focus:ring-1 focus:ring-primary"
        >
          <option value="">All instances</option>
          {instances.map((h) => (
            <option key={h} value={h}>{h}</option>
          ))}
        </select>

        <select
          value={filters.status || ''}
          onChange={(e) => setFilters({ status: e.target.value || null })}
          className="h-9 px-3 rounded-md border border-border bg-background text-sm focus:outline-none focus:ring-1 focus:ring-primary"
        >
          <option value="">All status</option>
          <option value="active">Active</option>
          <option value="idle">Idle</option>
          <option value="error">Error</option>
        </select>

        {hasFilters && (
          <button
            onClick={handleClear}
            className="h-9 px-3 rounded-md text-sm text-muted-foreground hover:text-foreground hover:bg-muted flex items-center gap-1.5"
          >
            <X className="size-3.5" />
            Clear
          </button>
        )}
      </div>
    </div>
  )
}

// frontend-svelte/src/lib/components/SessionFilters.svelte
<script lang="ts">
  import type { Session } from '$lib/types'
  import { store } from '$lib/store.svelte'
  
  interface Props {
    sessions: Session[]
  }
  
  let { sessions }: Props = $props()
  
  // Debounced search value
  let searchInput = $state('')
  let debounceTimer: ReturnType<typeof setTimeout> | null = null
  
  // Extract unique hostnames from sessions
  let hostnames = $derived(
    [...new Set(sessions.map(s => s.hostname).filter(Boolean))].sort()
  )
  
  // Count active filters (excluding directory which is handled by sidebar)
  let activeFilterCount = $derived(
    [store.filters.search, store.filters.status, store.filters.hostname]
      .filter(Boolean).length
  )
  
  // Check if any filter is active
  let hasActiveFilters = $derived(activeFilterCount > 0)
  
  // Debounced search handler
  function handleSearch(value: string) {
    searchInput = value
    if (debounceTimer) clearTimeout(debounceTimer)
    debounceTimer = setTimeout(() => {
      store.setFilter('search', value)
    }, 300)
  }
  
  // Clear all filters (except directory)
  function clearFilters() {
    searchInput = ''
    store.setFilter('search', '')
    store.setFilter('status', '')
    store.setFilter('hostname', '')
  }
</script>

<div class="flex items-center gap-3 flex-wrap">
  <!-- Search input -->
  <div class="relative flex-1 min-w-[200px] max-w-xs">
    <input
      type="text"
      placeholder="Search sessions..."
      bind:value={searchInput}
      oninput={(e) => handleSearch(e.currentTarget.value)}
      class="w-full px-3 py-2 text-sm rounded-md bg-[var(--bg-tertiary)] border border-[var(--border-subtle)] text-[var(--fg-primary)] placeholder:text-[var(--fg-muted)] focus:outline-none focus:border-[var(--accent-blue)] pr-8"
    />
    {#if searchInput}
      <button
        type="button"
        aria-label="Clear search"
        onclick={() => { searchInput = ''; store.setFilter('search', '') }}
        class="absolute right-2 top-1/2 -translate-y-1/2 text-[var(--fg-muted)] hover:text-[var(--fg-primary)] transition-colors"
      >
        <svg class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
        </svg>
      </button>
    {/if}
  </div>

  <!-- Status dropdown -->
  <select
    value={store.filters.status}
    onchange={(e) => store.setFilter('status', e.currentTarget.value)}
    class="px-3 py-2 text-sm rounded-md bg-[var(--bg-tertiary)] border border-[var(--border-subtle)] text-[var(--fg-primary)] focus:outline-none focus:border-[var(--accent-blue)] cursor-pointer"
  >
    <option value="">All status</option>
    <option value="active">Active</option>
    <option value="idle">Idle</option>
    <option value="error">Error</option>
    <option value="stale">Stale</option>
  </select>

  <!-- Hostname dropdown -->
  <select
    value={store.filters.hostname}
    onchange={(e) => store.setFilter('hostname', e.currentTarget.value)}
    class="px-3 py-2 text-sm rounded-md bg-[var(--bg-tertiary)] border border-[var(--border-subtle)] text-[var(--fg-primary)] focus:outline-none focus:border-[var(--accent-blue)] cursor-pointer"
  >
    <option value="">All hosts</option>
    {#each hostnames as hostname}
      <option value={hostname}>{hostname}</option>
    {/each}
  </select>

  <!-- Clear filters button + badge -->
  {#if hasActiveFilters}
    <button
      type="button"
      onclick={clearFilters}
      class="flex items-center gap-2 px-3 py-2 text-sm rounded-md bg-[var(--bg-tertiary)] border border-[var(--border-subtle)] text-[var(--fg-secondary)] hover:text-[var(--fg-primary)] hover:border-[var(--border)] transition-all"
    >
      <svg class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
      </svg>
      <span>Clear</span>
      <!-- Filter count badge -->
      <span class="px-1.5 py-0.5 text-xs font-medium rounded-full bg-[var(--accent-blue)]/20 text-[var(--accent-blue)]">
        {activeFilterCount}
      </span>
    </button>
  {/if}
</div>
