// frontend/src/components/sessions/session-card.tsx
// frontend/src/components/sessions/session-card.tsx
import { Circle, Clock, Server, Coins } from 'lucide-react'
import { cn, formatRelativeTime } from '@/lib/utils'
import type { Session } from '@/store'

interface SessionCardProps {
  session: Session
  onClick: () => void
  justUpdated?: boolean
}

const statusConfig = {
  active: { color: 'text-emerald-500', bg: 'bg-emerald-500', label: 'Active' },
  idle: { color: 'text-amber-500', bg: 'bg-amber-500', label: 'Idle' },
  error: { color: 'text-rose-500', bg: 'bg-rose-500', label: 'Error' },
  old: { color: 'text-muted-foreground', bg: 'bg-muted-foreground', label: 'Old' },
}

export function SessionCard({ session, onClick, justUpdated }: SessionCardProps) {
  const status = statusConfig[session.status] || statusConfig.old
  const needsAttention = session.needs_attention === 1

  return (
    <article
      onClick={onClick}
      className={cn(
        'group cursor-pointer rounded-lg border bg-card p-4 transition-all duration-150',
        'hover:bg-muted/50',
        justUpdated && 'ring-1 ring-primary',
        needsAttention ? 'border-amber-500/50' : 'border-border'
      )}
    >
      {/* Header */}
      <div className="flex items-start justify-between gap-3 mb-3">
        <div className="min-w-0 flex-1">
          <h3 className="text-sm font-medium truncate">{session.title}</h3>
          <div className="flex items-center gap-2 mt-1 text-xs text-muted-foreground">
            <Server className="size-3" />
            <span>{session.hostname}</span>
          </div>
        </div>
        
        {/* Status indicator */}
        <div className={cn('flex items-center gap-1.5 text-xs', status.color)}>
          <Circle className={cn('size-2', status.bg, 'rounded-full')} />
          <span>{status.label}</span>
        </div>
      </div>

      {/* Attention badge */}
      {needsAttention && (
        <div className="mb-3 px-2 py-1 rounded bg-amber-500/10 border border-amber-500/20 text-xs text-amber-500">
          Needs attention
        </div>
      )}

      {/* Footer */}
      <div className="flex items-center justify-between pt-3 border-t border-border text-xs text-muted-foreground">
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-1">
            <Coins className="size-3" />
            <span>{(session.token_total / 1000).toFixed(1)}k</span>
          </div>
          <span className="text-foreground font-medium">${session.cost_total.toFixed(2)}</span>
        </div>
        <div className="flex items-center gap-1">
          <Clock className="size-3" />
          <span>{formatRelativeTime(session.updated_at)}</span>
        </div>
      </div>
    </article>
  )
}

// frontend-svelte/src/lib/components/SessionCard.svelte
<script lang="ts">
  import type { Session } from '$lib/types'
  import { formatRelativeTime, formatTokens, formatCost, getProjectName, cn } from '$lib/utils'
  import StatusDot from './StatusDot.svelte'
  
  interface Props {
    session: Session
    selected?: boolean
  }
  
  let { session, selected = false }: Props = $props()
</script>

<a
  href="/sessions/{session.id}"
  class={cn(
    'block w-full text-left p-3 rounded-lg border transition-all duration-150',
    'hover:bg-[var(--bg-tertiary)] hover:border-[var(--border)]',
    selected 
      ? 'bg-[var(--bg-tertiary)] border-[var(--accent-blue)]' 
      : 'bg-[var(--bg-secondary)] border-[var(--border-subtle)]',
    session.needs_attention ? 'ring-1 ring-[var(--accent-amber)]' : ''
  )}
>
  <!-- Header row -->
  <div class="flex items-start justify-between gap-2 mb-2">
    <div class="flex items-center gap-2 min-w-0">
      <StatusDot status={session.status} />
      <span class="font-medium text-sm truncate text-[var(--fg-primary)]">
        {session.title || 'Untitled'}
      </span>
    </div>
    {#if session.needs_attention}
      <span class="shrink-0 px-1.5 py-0.5 text-[10px] font-medium rounded bg-[var(--accent-amber)]/20 text-[var(--accent-amber)]">
        ATTENTION
      </span>
    {/if}
  </div>

  <!-- Project & host -->
  <div class="flex items-center gap-2 text-xs text-[var(--fg-secondary)] mb-2">
    <span class="mono truncate">{getProjectName(session.directory)}</span>
    <span class="text-[var(--fg-muted)]">•</span>
    <span class="mono">{session.hostname}</span>
  </div>

  <!-- Footer: tokens, cost, time -->
  <div class="flex items-center justify-between text-xs">
    <div class="flex items-center gap-3 text-[var(--fg-muted)]">
      <span class="mono">{formatTokens(session.token_total || 0)} tok</span>
      <span class="mono">{formatCost(session.cost_total || 0)}</span>
    </div>
    <span class="mono text-[var(--fg-muted)]">{formatRelativeTime(session.updated_at)}</span>
  </div>
</a>
